#version 460

layout(binding = 0, rgba8) uniform readonly image2D inImage;
layout(binding = 1, rgba8) uniform writeonly image2D outImage;

layout(binding = 2) uniform sampler2D sceneDepth;

layout(binding = 3) readonly uniform UniformBuffer {
	mat4 view;
	mat4 projection;
	mat4 viewProjection;
    uint lightCount;
} uniformBuffer;

struct Light {
    vec4 position;
    vec4 colourIntensity;
    float near;
    float far;
};

layout(binding = 4) readonly buffer LightBuffer {
    Light[] lights;
} lightBuffer;

layout(push_constant) uniform PushConstants {
    float contrast;
    float brightness;
    float saturation;
    float exposure;
    float tonemapper;
    float gamma;
    bool drawLights;
} pushConstants;

// x * y * z <= 1024; must be true
layout(local_size_x = 32, local_size_y = 32, local_size_z = 1) in;

vec3 narkowiczACES(vec3 colour) {
    #define A 2.51
    #define B 0.03
    #define C 2.43
    #define D 0.59
    #define E 0.14
    return clamp((colour * (A * colour + B)) / (colour * (C * colour + D) + E), 0.0, 1.0);
}

void main() {
    #define x gl_GlobalInvocationID.x
    #define y gl_GlobalInvocationID.y
    vec3 colour = imageLoad(inImage, ivec2(x, y)).xyz;
    vec2 screenPosition = vec2(x, y) / imageSize(inImage);

    // Light halo effect
    if (pushConstants.drawLights) {
        for (uint i = 0; i < uniformBuffer.lightCount; i++) {
            vec4 lightPosition = uniformBuffer.viewProjection * lightBuffer.lights[i].position;
            lightPosition /= lightPosition.w;
            if (lightPosition.z <= texture(sceneDepth, screenPosition).r && lightPosition.z >= 0) {
                float distanceFromLight = (1 - lightPosition.z) / length(lightPosition.xy - (2 * screenPosition - 1));
                if (distanceFromLight < 1.0) {
                    colour += lightBuffer.lights[i].colourIntensity.xyz * distanceFromLight;
                }
            }
        }
    }

    colour = pushConstants.contrast * (colour - 0.5) + 0.5 + pushConstants.brightness;
    colour = max(colour, 0.0);

    float grayscale = dot(colour, vec3(0.299, 0.587, 0.114));
    colour = mix(vec3(grayscale), colour, pushConstants.saturation);
    colour *= pushConstants.exposure;

    switch (int(pushConstants.tonemapper)) {
        case 0:
            colour = narkowiczACES(colour);
            break;
        default:
            break;
    }

    imageStore(outImage, ivec2(x, y), vec4(pow(colour, vec3(1 / pushConstants.gamma)), 1.0));
}