package slang

// Severity of a diagnostic generated by the compiler.
Severity :: enum i32 {
	DISABLED = 0,
	NOTE     = 1,
	WARNING  = 2,
	ERROR    = 3,
	FATAL    = 4,
	INTERNAL = 5,
}

Warning_Level :: enum i32 {
	DEFAULT  = 0,
	ALL      = 1,
	EXTRA    = 2,
	PEDANTIC = 3,
}

Diagnostic_Flags :: distinct bit_set[Diagnostic_Flag; i32]
Diagnostic_Flag :: enum i32 {
	VERBOSE_PATHS            = 0,
	TREAT_WARNINGS_AS_ERRORS = 1,
}

Bindable_Resource_Type :: enum i32 {
	NON_BINDABLE  = 0,
	TEXTURE       = 1,
	SAMPLER       = 2,
	UNIFORM_BUFFER = 3,
	STORAGE_BUFFER = 4,
}

// NOTE: values must stay stable for binary compatibility with libslang, mirroring
// the ABI policy documented on SlangCompileTarget in slang.h.
Compile_Target :: enum i32 {
	UNKNOWN                     = 0,
	NONE                        = 1,
	GLSL                        = 2,
	HLSL                        = 5,
	SPIRV                       = 6,
	SPIRV_ASM                   = 7,
	DXBC                        = 8,
	DXBC_ASM                    = 9,
	DXIL                        = 10,
	DXIL_ASM                    = 11,
	C_SOURCE                    = 12,
	CPP_SOURCE                  = 13,
	HOST_EXECUTABLE             = 14,
	SHADER_SHARED_LIBRARY       = 15,
	SHADER_HOST_CALLABLE        = 16,
	CUDA_SOURCE                 = 17,
	PTX                         = 18,
	CUDA_OBJECT_CODE            = 19,
	OBJECT_CODE                 = 20,
	HOST_CPP_SOURCE             = 21,
	HOST_HOST_CALLABLE          = 22,
	CPP_PYTORCH_BINDING         = 23,
	METAL                       = 24,
	METAL_LIB                   = 25,
	METAL_LIB_ASM               = 26,
	HOST_SHARED_LIBRARY         = 27,
	WGSL                        = 28,
	WGSL_SPIRV_ASM              = 29,
	WGSL_SPIRV                  = 30,
	HOST_VM                     = 31,
	CPP_HEADER                  = 32,
	CUDA_HEADER                 = 33,
	HOST_OBJECT_CODE            = 34,
	HOST_LLVM_IR                = 35,
	SHADER_LLVM_IR              = 36,
}

Container_Format :: enum i32 {
	NONE         = 0,
	SLANG_MODULE = 1,
}

Pass_Through :: enum i32 {
	NONE             = 0,
	FXC              = 1,
	DXC              = 2,
	GLSLANG          = 3,
	SPIRV_DIS        = 4,
	CLANG            = 5,
	VISUAL_STUDIO    = 6,
	GCC              = 7,
	GENERIC_C_CPP    = 8,
	NVRTC            = 9,
	LLVM             = 10,
	SPIRV_OPT        = 11,
	METAL            = 12,
	TINT             = 13,
	SPIRV_LINK       = 14,
}

Archive_Type :: enum i32 {
	UNDEFINED    = 0,
	ZIP          = 1,
	RIFF         = 2,
	RIFF_DEFLATE = 3,
	RIFF_LZ4     = 4,
}

Compile_Flags :: distinct bit_set[Compile_Flag; u32]
Compile_Flag :: enum u32 {
	NO_MANGLING  = 3,
	NO_CODEGEN   = 4,
	OBFUSCATE    = 5,
}

Target_Flags :: distinct bit_set[Target_Flag; u32]
Target_Flag :: enum u32 {
	PARAMETER_BLOCKS_USE_REGISTER_SPACES = 4,
	GENERATE_WHOLE_PROGRAM                = 8,
	DUMP_IR                                = 9,
	GENERATE_SPIRV_DIRECTLY                = 10,
}

DEFAULT_TARGET_FLAGS :: Target_Flags{.GENERATE_SPIRV_DIRECTLY}

Floating_Point_Mode :: enum u32 {
	DEFAULT = 0,
	FAST    = 1,
	PRECISE = 2,
}

Fp_Denormal_Mode :: enum u32 {
	ANY      = 0,
	PRESERVE = 1,
	FTZ      = 2,
}

Line_Directive_Mode :: enum u32 {
	DEFAULT    = 0,
	NONE       = 1,
	STANDARD   = 2,
	GLSL       = 3,
	SOURCE_MAP = 4,
}

Source_Language :: enum i32 {
	UNKNOWN = 0,
	SLANG   = 1,
	HLSL    = 2,
	GLSL    = 3,
	C       = 4,
	CPP     = 5,
	CUDA    = 6,
	SPIRV   = 7,
	METAL   = 8,
	WGSL    = 9,
	LLVM    = 10,
}

Profile_ID :: distinct u32
PROFILE_UNKNOWN :: Profile_ID(0)

Capability_ID :: distinct i32
CAPABILITY_UNKNOWN :: Capability_ID(0)

Matrix_Layout_Mode :: enum u32 {
	UNKNOWN      = 0,
	ROW_MAJOR    = 1,
	COLUMN_MAJOR = 2,
}

Stage :: enum u32 {
	NONE           = 0,
	VERTEX         = 1,
	HULL           = 2,
	DOMAIN         = 3,
	GEOMETRY       = 4,
	FRAGMENT       = 5,
	COMPUTE        = 6,
	RAY_GENERATION = 7,
	INTERSECTION   = 8,
	ANY_HIT        = 9,
	CLOSEST_HIT    = 10,
	MISS           = 11,
	CALLABLE       = 12,
	MESH           = 13,
	AMPLIFICATION  = 14,
	DISPATCH       = 15,
	NODE           = 16,
	PIXEL          = FRAGMENT,
}

Debug_Info_Level :: enum u32 {
	NONE     = 0,
	MINIMAL  = 1,
	STANDARD = 2,
	MAXIMAL  = 3,
}

Debug_Info_Format :: enum u32 {
	DEFAULT = 0,
	C7      = 1,
	PDB     = 2,
	STABS   = 3,
	COFF    = 4,
	DWARF   = 5,
}

Optimization_Level :: enum u32 {
	NONE    = 0,
	DEFAULT = 1,
	HIGH    = 2,
	MAXIMAL = 3,
}

Emit_Spirv_Method :: enum i32 {
	DEFAULT    = 0,
	VIA_GLSL   = 1,
	DIRECTLY   = 2,
}

Emit_Cpu_Method :: enum i32 {
	DEFAULT  = 0,
	VIA_CPP  = 1,
	VIA_LLVM = 2,
}

Diagnostic_Color :: enum i32 {
	AUTO   = 0,
	ALWAYS = 1,
	NEVER  = 2,
}

Compile_Core_Module_Flags :: distinct bit_set[Compile_Core_Module_Flag; u32]
Compile_Core_Module_Flag :: enum u32 {
	WRITE_DOCUMENTATION = 0,
}

Builtin_Module_Name :: enum i32 {
	Core = 0,
	GLSL = 1,
}

Session_Flags :: distinct u32
SESSION_FLAGS_NONE :: Session_Flags(0)

Container_Type :: enum i32 {
	None             = 0,
	UnsizedArray     = 1,
	StructuredBuffer = 2,
	ConstantBuffer   = 3,
	ParameterBlock   = 4,
}

Layout_Rules :: enum u32 {
	Default                  = 0,
	MetalArgumentBufferTier2 = 1,
	DefaultStructuredBuffer  = 2,
	DefaultConstantBuffer    = 3,
}
